const subjects = [
  "signal",
  "message",
  "cipher",
  "transmission",
  "system",
  "node",
  "packet",
  "channel",
  "network",
  "protocol",
  "beacon",
  "archive",
  "gateway",
  "link",
  "sensor",
  "terminal",
  "sequence",
  "relay",
  "matrix",
  "console",
  "payload",
  "wave",
  "mirror",
  "orbit",
  "cluster",
  "core",
  "vector",
  "frame",
  "signal tower",
  "hive",
  "drone",
  "node array",
  "beacon burst",
  "data stream",
  "trace",
  "source",
  "sector",
  "interface",
  "portal",
  "gateway link",
  "relay hub",
  "fiber",
  "shadow",
  "glitch",
  "uplink",
  "downlink",
  "control grid",
  "quantum relay",
  "black channel",
  "ghost signal",
  "deep archive",
  "echo node",
  "neural lattice",
  "observer unit",
  "monitor array",
  "tracking beacon",
  "pulse engine",
  "frequency shard",
  "spectrum core",
  "sync tower",
  "carrier wave",
  "repeater",
  "transit loop",
  "memory bank",
  "data vault",
  "watchtower",
  "phantom relay",
  "silent broadcast",
  "null sector",
  "static field",
  "sync pulse",
  "transceiver",
  "phase array",
  "compression node",
  "navigation core",
];

const verbs = [
  "is broken",
  "is hidden",
  "was intercepted",
  "has failed",
  "is unstable",
  "was encoded",
  "is compromised",
  "is disrupted",
  "was corrupted",
  "is delayed",
  "is offline",
  "is encrypted",
  "is leaking",
  "is fractured",
  "was rerouted",
  "is collapsing",
  "is glitched",
  "is masked",
  "is fragmented",
  "was redirected",
  "has vanished",
  "is impaired",
  "is scrambled",
  "has broken down",
  "was duplicated",
  "is overloaded",
  "is misaligned",
  "is locked",
  "is trapped",
  "was suppressed",
  "is distorted",
  "is eroded",
  "was frozen",
  "is clouded",
  "is stalled",
  "was severed",
  "is scattered",
  "was shadowed",
  "is drifting",
  "is oscillating",
  "has desynced",
  "is decaying",
  "was quarantined",
  "is deteriorating",
  "is fading",
  "was neutralized",
  "has diverged",
  "is contaminated",
  "was erased",
  "is mutating",
  "has inverted",
  "is trapped in recursion",
  "is fluctuating",
  "is resonating",
  "has gone silent",
  "was rewritten",
  "is phasing out",
  "is destabilizing",
  "is infected",
  "has crossed the boundary",
];

const objects = [
  "in the network",
  "under the surface",
  "beyond the grid",
  "inside the archive",
  "across the channel",
  "within the loop",
  "behind the firewall",
  "beneath the signal",
  "in the matrix",
  "around the node",
  "past the gateway",
  "through the relay",
  "inside the console",
  "beneath the protocol",
  "within the sequence",
  "above the code",
  "below the surface",
  "behind the mirror",
  "inside the packet",
  "across the wave",
  "near the sensor",
  "through the terminal",
  "along the orbit",
  "inside the core",
  "inside the spectrum",
  "along the vector",
  "within the shadow",
  "beneath the grid",
  "behind the interface",
  "before the portal",
  "inside the relay hub",
  "across the node array",
  "inside the frame",
  "through the fiber",
  "within the burst",
  "inside the trace",
  "beyond the sector",
  "inside the static",
  "beneath the carrier wave",
  "within corrupted storage",
  "inside the dead zone",
  "through the black channel",
  "inside the vault",
  "within the recursion loop",
  "inside the anomaly",
  "past the signal horizon",
  "inside the breach",
  "through the static storm",
  "inside quarantine",
  "within signal decay",
  "beneath the echo layer",
];

const imperatives = [
  "trust no one",
  "decode carefully",
  "follow the pattern",
  "observe the noise",
  "break the loop",
  "secure the channel",
  "ignore the glitch",
  "track the source",
  "scan the grid",
  "maintain signal",
  "avoid the trap",
  "hold the line",
  "shield the node",
  "bypass the firewall",
  "collect the packet",
  "decrypt the code",
  "trace the relay",
  "stabilize the network",
  "reboot the system",
  "evade detection",
  "restore the link",
  "save the backup",
  "monitor the feed",
  "seal the breach",
  "secure the perimeter",
  "reroute the stream",
  "prime the beacon",
  "detach the node",
  "reset the matrix",
  "scan for shadows",
  "lift the distortion",
  "guard the archive",
  "probe the channel",
  "close the gateway",
  "watch the flux",
  "unfreeze the feed",
  "return to base",
  "do not trust the relay",
  "silence the beacon",
  "avoid mirrored signals",
  "verify the checksum",
  "recover the archive",
  "contain the breach",
  "disconnect immediately",
  "do not answer the transmission",
  "disable the observer node",
  "purge corrupted memory",
  "remain off-grid",
  "terminate the signal",
  "lock the vault",
  "maintain radio silence",
  "track the phantom relay",
];

export function generatePhrase(rand: () => number) {
  const type = Math.floor(rand() * 2);

  if (type === 0) {
    const s = subjects[Math.floor(rand() * subjects.length)];
    const v = verbs[Math.floor(rand() * verbs.length)];
    const o = objects[Math.floor(rand() * objects.length)];

    return `${s.toUpperCase()} ${v.toUpperCase()} ${o.toUpperCase()}`;
  }

  return imperatives[Math.floor(rand() * imperatives.length)].toUpperCase();
}
